version: "3.9"
services:
  db:
    container_name: db-Proyecto_Web
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: Proyecto_Web_db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel1234
    networks:
      - net-Proyecto_Web
  web:
    container_name: Proyecto_Web-web
    depends_on:
      - db
    ports:
      - "8083:80"
    volumes:
      - "./web:/var/www/html"
      - "./httpd.conf:/etc/httpd/conf/httpd.conf"
    image: laravel-php8
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - net-Proyecto_Web
networks:
  net-Proyecto_Web:
    
